name: BrokersContracts

on:
  push:
    branches: [master, develop]
    paths:
      - "src/shared/Flour.BrokersContracts/**"
      - "src/tests/Flour.BrokersContracts.Tests/**"
      - ".github/workflows/brokers-contracts.yml"
env:
  PROJ_FOLDER: src/shared/Flour.BrokersContracts
  PROJ_FILE: src/shared/Flour.BrokersContracts/Flour.BrokersContracts.csproj
  TEST_PROJ_FILE: src/tests/Flour.BrokersContracts.Tests/Flour.BrokersContracts.Tests.csproj

jobs:
  allInOne:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302
      - name: Install dependencies
        run: dotnet restore $PROJ_FILE
      - name: Build
        run: dotnet build --configuration Release $PROJ_FILE
      - name: Test
        id: tests
        run: dotnet test --verbosity normal $TEST_PROJ_FILE
      - name: Tests successed
        if: success()
        id: tests_success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Tests succeeded. ${{ join(steps.tests.outputs.*, '\n') }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Tests failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Tests failed.
          text: ${{ join(steps.tests.outputs.*, '\n') }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Publish
        if: ${{ success() }}
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ./$PROJ_FILE
          VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
          TAG_FORMAT: '*'
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
