name: Logging

on:
  push:
    branches: [master, develop]
    paths:
      - "src/shared/Flour.Logging/**"
      - "src/tests/Flour.Logging.Tests/**"
      - ".github/workflows/logging.yml"
env:  
  PROJ_DIR: src/shared/Flour.Logging/
  PROJ_FILE: src/shared/Flour.Logging/Flour.Logging.csproj
  PROJ_VERSION_FILE: src/shared/Flour.Logging/version.json
  TEST_PROJ_FILE: src/tests/Flour.Logging.Tests/Flour.Logging.Tests.csproj

jobs:
  allInOne:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302
      - name: Install dependencies
        run: dotnet restore $PROJ_FILE
      - name: Build
        run: dotnet build --configuration Release $PROJ_FILE
      - name: Test
        id: tests
        run: dotnet test --verbosity normal $TEST_PROJ_FILE
      - name: Tests successed
        if: success()
        id: tests_success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Tests succeeded. ${{ join(steps.tests.outputs.*, '\n') }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Tests failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Tests failed.
          text: ${{ join(steps.tests.outputs.*, '\n') }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Pack
        if: ${{ success() }}
        run: cd $PROJ_DIR | dotnet pack -o nuget-packages -v n -c Release
      - name: Publish
        if: ${{ success() }}
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
