name: Logging

on:
  push:
    branches: [master, develop]
    paths:
      - "src/shared/Flour.Logging/**"
      - "src/tests/Flour.Logging.Tests/**"
      - ".github/workflows/logging.yml"
env:  
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PROJECT_NAME: Flour.Logging

jobs:
  build:
    name: Build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
      - name: 'Git Fetch Tags'
        run: git fetch --tags 
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: 'Go to libs folder'
        run: cd 
      - name: 'Dotnet Tool Restore'
        run: dotnet tool restore
      - name: 'Dotnet Cake Build'
        run: dotnet cake --target=Build --project=$PROJECT_NAME
      - name: 'Dotnet Cake Test'
        run: dotnet cake --target=Test --project=$PROJECT_NAME
      - name: 'Dotnet Cake Pack'
        if: success()
        run: dotnet cake --target=Pack --project=$PROJECT_NAME
      - name: 'Publish Artefacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{matrix.os}}
          path: './nugets'

  push-nuget:
    name: 'Push NuGet Packages'
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download Artefact'
        uses: actions/download-artifact@v1
        with:
          name: 'ubuntu-latest'
      - name: 'Dotnet NuGet Push'
        run: dotnet nuget push nugets/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate